services:
  postgres:
    image: postgres:16
    container_name: Datastore-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12342
      POSTGRES_DB: Datastore
    ports:
      - "5432:5432"
    volumes:
      - Datastore:/var/lib/postgresql/data

  fastapi:
    build: /api
    container_name: store-api
    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: postgresql://postgres:12342@postgres:5432/Datastore

    depends_on:
      - postgres

    volumes:
      - /app:/app
  
  
  frontend:
    build:
      context: ./frontend/client
    container_name: frontend
    ports:
    - "5173:5173"
    depends_on:
    - fastapi

volumes:
  Datastore:


