FROM node:20-alpine 

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
#RUN npm run build

#FROM nginx:stable-alpine AS production
#COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 5173
CMD ["npm", "run","dev","--","--host","0.0.0.0"]
