"""initialize schema into docker contaner

Revision ID: caca135a4659
Revises: dbf192d2a467
Create Date: 2026-07-17 15:03:30.535051
"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy.dialects.postgresql as postgresql

# revision identifiers
revision = 'caca135a4659'
down_revision = 'dbf192d2a467'
branch_labels = None
depends_on = None


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('items')
    op.drop_table('carts')
    op.drop_table('cart_items')
    op.drop_table('orders')
    op.drop_table('users')
    # ### end Alembic commands ###


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False),
    sa.CheckConstraint("status::text = ANY (ARRAY['suspended'::character varying, 'inactive'::character varying, 'active'::character varying]::text[])", name='users_status_check'),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('orders_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('total_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_date', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint('total_price >= 0::numeric', name='orders_total_price_check'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='orders_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='orders_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('items_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.CheckConstraint('price >= 0::numeric', name='items_price_check'),
    sa.CheckConstraint('quantity >= 0', name='items_quantity_check'),
    sa.PrimaryKeyConstraint('id', name='items_pkey'),
    sa.UniqueConstraint('name', name='items_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('carts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cart_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='carts_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='carts_pkey'),
    sa.UniqueConstraint('user_id', name='carts_user_id_key')
    )
    op.create_table('cart_items',
    sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('quantity > 0', name='cart_items_quantity_check'),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], name='cart_items_cart_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name='cart_items_item_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cart_id', 'item_id', name='cart_items_pkey')
    )
    
    op.create_table('order_items',
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price_at_order', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.CheckConstraint('price_at_order >= 0::numeric', name='order_items_price_at_order_check'),
    sa.CheckConstraint('quantity > 0', name='order_items_quantity_check'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name='order_items_item_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='order_items_order_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_id', 'item_id', name='order_items_pkey')
    )
    # ### end Alembic commands ###